### ISSUE TITLE
Should we get rid of the keepers folder to make our code more closely match sdk simapp, ibc simapp, and wasmd?

### ISSUE THREAD

**Issue by faddat** [quicksilver-zone/quicksilver#1031]
the keepers folder takes us away from what seems to be a standard way of building in cosmos.  Should we fix this?

Is it considered a problem?  I find it easier without.

**Comment by joe-bowman** [comment]
Do you mean app/keepers? It was added to get rid of the hugely unwieldy app.go that is thousands of lines long. Gaia, Osmosis and Juno follow the same pattern.

**Comment by faddat** [comment]
Yep.  Ok -- over time, I came to disfavor that pattern, which I also helped popularize.  But this is totally nbd, and if you prefer the current form let us continue with it.  

PS:

Yes, the app.go would then become too long.  Tradeoffs....
