### ISSUE TITLE
Add claims onboarding data in upgradehandler

### ISSUE THREAD

**Issue by joe-bowman** [quicksilver-zone/quicksilver#1146]
## Summary

In order to remove the need to raise a LOT of governance props to onboard all aspects of claims, we should circumvent this by adding via the upgrade handler.

We need to add:

- connections
- osmosis params
- local denoms
- denoms on host zones
- denoms on osmosis
- denoms on umee
- osmosis pools

**Comment by tropicaldog** [comment]
@joe-bowman  Can you confirm if my understanding of the issue is correct? Is the scope of this issue to add new logic to update or add one or more `ProtocolData` as part of the v1.5.0 upgrade?

**Comment by joe-bowman** [comment]
Yes this is correct.
