### ISSUE TITLE
x/claimsmanager/keeper: bytes.Index results should be checked before blindly assuming each key will always have 0x00,0x00 lest could cause a runtime panic from index out of bounds

### ISSUE THREAD

**Issue by odeke-em** [quicksilver-zone/quicksilver#1217]
## Summary of Bug
While auditing this module I noticed this code https://github.com/quicksilver-zone/quicksilver/blob/7966553ea6915777e87245a6c58ee467bc7ae979/x/claimsmanager/keeper/grpc_query.go#L73-L75 and https://github.com/quicksilver-zone/quicksilver/blob/7966553ea6915777e87245a6c58ee467bc7ae979/x/claimsmanager/keeper/grpc_query.go#L90-L92

Which assume that every single key will be properly formed and have the bytes in search. However, this could cause a runtime panic and take down the caller if at all we have any key that doesn't conform to that structure and could return a not found index. Sure +1 is always added to skip the separator but that's just gonna cause data corruption from the wrong result and say for example a key was of length 0, formed by one tampering with the database or innocently included due to some coding error somewhere, this will cause a runtime panic that could have been trivially avoided just by ensuring that bytes.Index returns a value >= 0

## Expected Behaviour
Firstly check that the index >= 0

/cc @joe-bowman @faddat 

____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [x] Appropriate contributors tagged/assigned

**Comment by faddat** [comment]
sir, @odeke-em thank you very much for your review

**Comment by odeke-em** [comment]
Thanks for the fix but it isn't correct :-) The problem was checking on bytes.Index but not on idx, it should be
```go
idx := bytes.Index(key[1:], []byte{0x00})
if idx >= 0 {
     idx += 1 + 1 // Cater to skip the separator.
     if bytes.Equal(key[idx:idx+len(addrBytes)], addrBytes) {
         out = append(out, claim)
     }
}
```

**Comment by odeke-em** [comment]
I've mailed out PR https://github.com/quicksilver-zone/quicksilver/pull/1234
