### ISSUE TITLE
Research: determine raw kv store key for CW data structures

### ISSUE THREAD

**Issue by joe-bowman** [quicksilver-zone/quicksilver#1647]
## Summary

In order to integrate with projects implemented in CosmWasm, we need to be able to query via ICQ data structures those contracts use. In order to do this, we need to be able to determine the key at the which the data is stored in the KV store. With the key, we are able to make an ICQ request for the data, and will be able to reassemble / validate / interpret the data on the QS side to be able to attribute ownership over assets.

So far, I have looked at cw-storage-plus, cosmwasm_std::storage_keys, and wasmd.

From wasmd, I get that the store prefix should be 0x03 + contract_address_bytes
From storage_keys/storage-plus, I ascertain that a key is created from parts, with each part being prefixed by it's length expressed as two bytes, such that:

key(A,B,C) would be be 0x00016500016667 (I believe!!)

I am currently interested in getting the value of a nolus loan for a user:

https://github.com/nolus-protocol/nolus-money-market/blob/85ac288fad3218447be26039b14f4dcbf6affb10/protocol/contracts/lpp/src/loan.rs#L86

which is defined as:
```
const STORAGE: Map<'static, Addr, Loan<Lpn>> = Map::new("loans");
...
    pub fn load(storage: &dyn Storage, addr: Addr) -> Result<Self> {
        Self::STORAGE.load(storage, addr).map_err(Into::into)
    }
```

which by my reckoning, should be:

0x03 + contract_addr_bytes + 0x0005 + "loans" + user_addr_bytes

but my attempts thus far return nil

```
Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import bech32
>>> import binascii
>>> contract_addr = "nolus1dca9sf0knq3qfg55mv2sn03rdw6gukkc4n764x5pvdgrgnpf9mzsfkcjp6"
>>> contract_58 = bech32.bech32_decode(contract_addr)
>>> contract_bytes = bech32.convertbits(contract_58, 5, 8)
>>> len(contract_bytes)
33
>>> store_prefix = [0x03] + list(contract_bytes)
>>> my_addr = "nolus1jc24kwznud9m3mwqmcz3xw33ndjuufngpqmzld"
>>> _, my_58 = bech32.bech32_decode(my_addr)
>>> my_bytes = bech32.convertbits(my_58, 5, 8)
>>> len(my_bytes)
20
key_bytes = store_prefix + [0x00, 0x05] + list("loans".encode(encoding="utf-8")) + list(my_bytes)
binascii.hexlify(bytes(key_bytes))
b'036e3a5825f6982204a294db1509be236bb48e5ad8acfdaa9a816350344c292ec50000056c6f616e7396155b3853e34bb8edc0de05133a319b65ce2668'
```
then
```
cat >> payload
{
  "jsonrpc": "2.0",
  "id": 864499175752,
  "method": "abci_query",
  "params": {
    "path": "/store/wasm/key",
    "data": "036e3a5825f6982204a294db1509be236bb48e5ad8acfdaa9a816350344c292ec50000056c6f616e7396155b3853e34bb8edc0de05133a319b65ce2668",
    "prove": false
  }
}
<ctrl+d>

> curl -d @payload https://pirin-cl.nolus.network:26657/ -H 'Content-Type: application/json'

{"jsonrpc":"2.0","id":864499175752,"result":{"response":{"code":0,"log":"","info":"","index":"0","key":"A246WCX2mCIEopTbFQm+I2u0jlrYrP2qmoFjUDRMKS7FAAAFbG9hbnOWFVs4U+NLuO3A3gUTOjGbZc4maA==","value":null,"proofOps":null,"height":"5615526","codespace":""}}}
```

should return a non-nil value (but it doesn't, meaning my key derivation is off somewhere!)

**Comment by tropicaldog** [comment]
> 0x03 + contract_addr_bytes + 0x0005 + "loans" + user_addr_bytes

By logging out the key in the the `binaryd q wasm contract-state all <contract address>` command, I believe this is correct, but I am also unable to query via rpc. Will try to make a query in go code.

**Comment by kienn6034** [comment]
@joe-bowman @tropicaldog 
https://github.com/notional-labs/wasmd/blob/feat/query-key-from-module/x/wasm/keeper/keeper.go#L728-L733
i add this code to the `query smart`  query, to construct the key of this [counter](https://github.com/notional-labs/wasmd/blob/feat/query-key-from-module/scripts/counter/src/state.rs#L14) contract, which stores a mapping of `user` to a `count`, with namespace `state`

**Comment by kienn6034** [comment]
how to query using rpc:
1. Run the node, and deploy the counter contract + increment the value `./testnode.sh wasmd`
2. Get the contract address, replace to the `prefix-counter.py`,
3. query using the output of steps 2 `./test-query-node.sh 036bbef764c1c7ef8e4471131f6609e844143b57b483321e9801db942de0bfaaba000573746174657761736d31686a35667665657235636a746e347764367773747a75676a6664787a6c307870767372383967`

**Comment by kienn6034** [comment]
your key derivation is correct @joe-bowman , there is just a small problem with the python script to generate the key. I tested using the counter, with `pub const COUNTERS: Map<Addr, Counter> = Map::new("state");` this state, i believe we can apply the same of the other contract
