### ISSUE TITLE
Logging for icq-relayer

### ISSUE THREAD

**Issue by joe-bowman** [quicksilver-zone/quicksilver#1657]
## Summary

Currently, the icq-relayer uses at least three different ways of logging, and this should be refactored to use one such library.

Note: build on `icq/v1.0.x branch`, and not `main`, please!

**Comment by trungnt1811** [comment]
hi @joe-bowman please assign this issue to me

**Comment by joe-bowman** [comment]
merged into icq-relayer/v1.0.0
