### ISSUE TITLE
icq: default config is written to wrong location

### ISSUE THREAD

**Issue by joe-bowman** [quicksilver-zone/quicksilver#1683]
## Summary of Bug

Config is loaded from the literal path '~'/.icq, instead of being expanded to /home/$USER/.icq - missing os.expandPath() somewhere? 
## Expected Behaviour

Config is loaded and written to relative to user home directory, not a directory named "~" inside the cwd.

## Version

f35b3c1d3cb72d875a3d984c02d45a71a76e41ce

## Steps to Reproduce

```
make build
./icq-relayer start <key>
```

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by joe-bowman** [comment]
@hoank101 - I believe this is a bug in your PR #1665

**Comment by hoank101** [comment]
thank @joe-bowman  , i have a PR to fix this issue
