### ISSUE TITLE
icq: keys are read from wrong home folder

### ISSUE THREAD

**Issue by joe-bowman** [quicksilver-zone/quicksilver#1684]
## Summary of Bug

Running `./icq-relayer keys list` returns keys stored under ~/.quicksilverd

## Expected Behaviour

Keys should live under ~/.icq

## Version

f35b3c1d3cb72d875a3d984c02d45a71a76e41ce

**Comment by joe-bowman** [comment]
@hoank101 - also related to #1665

**Comment by hoank101** [comment]
hi @joe-bowman i think it is not issues
you can see default flag  `--keyring-backend string   Select keyring's backend (os|file|test) (default "os")`
you can using command 
`./icq-relayer keys list --keyring-backend test --home ~/.icq`
