### ISSUE TITLE
Update `x/mint` module spec

### ISSUE THREAD

**Issue by aljo242** [quicksilver-zone/quicksilver#288]
Context: https://github.com/ingenuity-build/quicksilver/tree/main/x/mint/spec

The current spec `README` contains information about osmosis and OSMO tokens.  Credit should still be given to osmosis, but the contents can be modified a bit more to be specific for quicksilver and QCK.

**Comment by ajansari95** [comment]
yes, we have the attribution [here](https://github.com/ingenuity-build/quicksilver#origination-and-attribution), so it should be changed as per scope of Quicksilver. @joe-bowman
