### ISSUE TITLE
collect-gentxs fails on branch: update/sdk47

### ISSUE THREAD

**Issue by muku314115** [quicksilver-zone/quicksilver#452]
## Summary of Bug
after the normal setup to run a node, collect-gentxs returns the attached error
<img width="1440" alt="Screenshot 2023-06-08 at 6 37 10 PM" src="https://github.com/ingenuity-build/quicksilver/assets/44918265/f3e9ccbc-b884-4c39-ac35-e723a020d0d0">

This problem does not exist on develop

## Steps to Reproduce

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by joe-bowman** [comment]
This seems to be resolved now; can you confirm @muku314115 ?
