### ISSUE TITLE
[quicksilverjs] Should use latest release of telescope

### ISSUE THREAD

**Issue by faddat** [quicksilver-zone/quicksilver#595]
recently we updated the quicksilverjs folder in this repository. 

* it doesn't seem to build (but I could be doing that wrong)
* it doesn't use the latest release of telescope (but is there a compatiblity problem?)

**Comment by hoangdv2429** [comment]
For now it's only minor changes of telescope. After I fix the metioned bugs, I'll upgrade it with latest version.

**Comment by chalabi2** [comment]
let me know if you need me on this @hoangdv2429 ?

**Comment by hoangdv2429** [comment]
@chalabi2 https://github.com/quicksilver-zone/quicksilver/pull/566#event-10382653789 I have listed all the tasks that need to be working on before upgrade to new telescope. If you interested in any task please create a issue and self-assign and tag me in
