### ISSUE TITLE
x/interchainstaking: Keeper.GetChainID should use the safe quoting %q format specifier and not \"%s\" in fmt.Errorf

### ISSUE THREAD

**Issue by odeke-em** [quicksilver-zone/quicksilver#606]
## Summary of Bug
This code https://github.com/quicksilver-zone/quicksilver/blob/bbf9ef90b82b0afde218e146d5c3c94da867c4dd/x/interchainstaking/keeper/keeper.go#L431-L444 creates a custom quoted message `\"%s\"` but the "%q" format specifier already exists, so please use that.

## Version
13bf586baffd07ca4a2a7f093212455fafb5df27

____

#### For Admin Use

- [x] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by ThanhNhann** [comment]
Hey @faddat, how is going with this issue?
