### ISSUE TITLE
x/interchainstaking: Keeper.EmitValidatorQuery should check that the ValidatorOperatorAddress is a correct bech32 address and also return an error

### ISSUE THREAD

**Issue by odeke-em** [quicksilver-zone/quicksilver#609]
## Summary of Bug
If at all the wrong operator address is passed in mistakenly, EmitValidatorQuery should be able to reject it and not emit the query but currently it assumes the address will always be bech32 per
https://github.com/quicksilver-zone/quicksilver/blob/c26b22e7cf2eebef24f70289f73552f54da807ea/x/interchainstaking/keeper/keeper.go#L500-L501

## Suggestion
Let's modify that signature of that method and then also check for errors returned
```go
_, addr, err := bech32.DecodeAndConvert(validator.OperatorAddress)
if err != nil {
   return fmt.Errorf("EmitValidatorQuery failed to decode validator.OperatorAddress: %q got error: %w",
         validator.OperatorAddress, err)
}
````

## Version

13bf586baffd07ca4a2a7f093212455fafb5df27

/cc @elias-orijtech 

____

#### For Admin Use

- [x] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by ThanhNhann** [comment]
`Keeper.EmitValidatorQuery` is just used in `Keeper.SetValidatorsForZone` and I see QS have the check correct bech32 address [here](https://github.com/quicksilver-zone/quicksilver/blob/7874b7073baaacee87a169c0943307db4553ebf6/x/interchainstaking/keeper/keeper.go#L219) so I don't think we need check more here
cc: @joe-bowman

**Comment by joe-bowman** [comment]
Agree with @ThanhNhann that with current usage, the check is there in the parent fn.

Also agree with @odeke-em that if we use this elsewhere in the future, it puts the onus on the developer as it stands to ensure the correct error checking is done higher up. As we are already calling `bech32.DecodeAndConvert()` (actually this probably ought to use our corresponding function in `addressutils` package, for consistency) and we have the error to hand, bubbling it up the stack is better for future safety.
