### ISSUE TITLE
all, x/interchainstaking/keeper: create and use variables closest to where they are used

### ISSUE THREAD

**Issue by odeke-em** [quicksilver-zone/quicksilver#611]
## Summary of Bug
This is a stylistic nit for Go code in which code and variables should only be declared closest to where it is used. For example please see

https://github.com/quicksilver-zone/quicksilver/blob/c26b22e7cf2eebef24f70289f73552f54da807ea/x/interchainstaking/keeper/callbacks.go#L108-L113

which should be

```go
 if len(query.Request) == 0 { 
 	return errors.New("attempted to unmarshal zero length byte slice (2)") 
 } 

 // unmarshal request payload 
 rewardsQuery := new(distrtypes.QueryDelegationTotalRewardsRequest)
 err := k.cdc.Unmarshal(query.Request, rewardsQuery) 
```

https://github.com/quicksilver-zone/quicksilver/blob/c26b22e7cf2eebef24f70289f73552f54da807ea/x/interchainstaking/keeper/callbacks.go#L133-L137

```go
 if len(query.Request) == 0 { 
 	return errors.New("attempted to unmarshal zero length byte slice (3)") 
 } 

 delegationQuery := new(stakingtypes.QueryDelegatorDelegationsRequest)
 err := k.cdc.Unmarshal(query.Request, &delegationQuery) 
```

and many others!

## Version
086d2e6e571e0a51c5751fb2223a7361b57dd480

____

#### For Admin Use

- [x] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by odeke-em** [comment]
We need to also fix this https://github.com/quicksilver-zone/quicksilver/blob/c26b22e7cf2eebef24f70289f73552f54da807ea/x/interchainstaking/keeper/callbacks.go#L431-L442

like this

```go
 queryRequest := tx.GetTxRequest{} 
 if err := k.cdc.Unmarshal(query.Request, &queryRequest); err != nil {
 	return err 
 } 
  
 // check tx is valid for hash. 
 hash := tmhash.Sum(res.Proof.Data) 
 hashStr := hex.EncodeToString(hash) 
 if !strings.EqualFold(hashStr, queryRequest.Hash) { 
```

**Comment by ThanhNhann** [comment]
hey @sontrinh16, any updates for this issue?
