### ISSUE TITLE
x/interchainstaking/keeper: should Keeper.DelegationCallback check that the validator is not jailed nor tombstoned?

### ISSUE THREAD

**Issue by odeke-em** [quicksilver-zone/quicksilver#612]
## Summary of Bug
Just reading through this code https://github.com/quicksilver-zone/quicksilver/blob/c26b22e7cf2eebef24f70289f73552f54da807ea/x/interchainstaking/keeper/callbacks.go#L189-L196 I wonder if perhaps we shouldn't successfully complete the callback if the validator is jailed or tombstoned?

## Version
086d2e6e571e0a51c5751fb2223a7361b57dd480

____

#### For Admin Use

- [x] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by joe-bowman** [comment]
It feels too late at this point to make this check, as the delegation has already been actioned on the host chain here. This should already be happening in `DeterminePlanForDelegation()`
