### ISSUE TITLE
x/interchainstaking/keeper: Keeper.CheckTMHeaderForZone is untested and unused

### ISSUE THREAD

**Issue by odeke-em** [quicksilver-zone/quicksilver#614]
## Summary of Bug
I don't see any usage of Keeper.CheckTMHeaderForZone and its coverage reports show it heavily untested. If it is to be kept around, please test it.

## Version
13bf586baffd07ca4a2a7f093212455fafb5df27

____

#### For Admin Use

- [x] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by joe-bowman** [comment]
Usage is fixed in #639

**Comment by hoangdv2429** [comment]
I believe this will be solve together with #615
