### ISSUE TITLE
x/interchainstaking/keeper: untested handlers HandleCompleteSend, GCCompletedRedelegations, HandleTokenizedShares, DistributeRewardsFromWithdrawAccount, TriggerRedemptionRate, HandleWithdrawRewards, GetValidatorForToken, HandleRedeemTokens, HandleFailedUnbondSend, HandleFailedBankSend

### ISSUE THREAD

**Issue by odeke-em** [quicksilver-zone/quicksilver#617]
## Summary of Bug
These handlers are untested:
- [x] Keeper.HandleCompleteSend
- [x] Keeper.GCCompletedRedelegations
- [ ] Keeper.HandleTokenizedShares
- [x] Keeper.DistributeRewardsFromWithdrawAccount
- [x] Keeper.TriggerRedemptionRate
- [ ] Keeper.HandleWithdrawRewards
- [x] Keeper.GetValidatorForToken
- [x] Keeper.HandleRedeemTokens
- [x] Keeper.HandleFailedUnbondSend
- [x] Keeper.HandleFailedBankSend
- [x] msgServer.GovReopenChannel
- [x] msgServer.GovCloseChannel
- [ ] Keeper.HandleUpdateZoneProposal
- [ ] Keeper.EnsureWithdrawalAddresses
- [ ] Keeper.RemoveZoneAndAssociatedRecords
- [x] Keeper.GetActiveValidators
- [x] Keeper.SendTokenIBC
- [ ] Keeper.DeleteRedelegationRecordByKey
- [x] Keeper.GCCompletedUnbondings
- [x] Keeper.DeleteRedelegationRecordByKey
- [ ] Keeper.HandleUpdateZoneProposal
- [x] Keeper.Zone
- [x] Keeper.IteratePortConnections
- [x] Keeper.GetChainIDFromContext
- [x] PerfBalance
- [x] #710

## Version
13bf586baffd07ca4a2a7f093212455fafb5df27

____

#### For Admin Use

- [x] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by hoangdv2429** [comment]
@DongLieu will take care of TestPerfBalanceCallback

**Comment by neitdung** [comment]
We need to close #654 before write test for  **Keeper.HandleTokenizedShares**

**Comment by neitdung** [comment]
Hey @ThanhNhann and @joe-bowman, I think Keeper.EnsureWithdrawalAddresses should be tested by interchain test. Because this function just return error when SubmitTx, every validations just return nil.
https://github.com/quicksilver-zone/quicksilver/blob/543f819670378f1be207be43054514583c7de99d/x/interchainstaking/keeper/zones.go#L190-#L233

**Comment by ThanhNhann** [comment]
Hey @anhductn2001, can you make an `interchaintest` for `Keeper.EnsureWithdrawalAddresses`, it's like we can't test it by unit test with the cmt of @neitdung above

**Comment by anhductn2001** [comment]
Okey, let me see @ThanhNhann
