### ISSUE TITLE
Add `ICQ` to get info of `Validator`

### ISSUE THREAD

**Issue by ThanhNhann** [quicksilver-zone/quicksilver#640]
## Summary

- We should add an `ICQ` to get info of `Validator` to look up the validator sign info when to check whether `Validator` was `Tombstone` or not

#### For Admin Use

- [x] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by joe-bowman** [comment]
Thank you. So in `SetValidatorForZone`, if a validator was _not_ jailed, and now _is_ (we already have a conditional for this), we should trigger an ICQ request to look up the SiginingInfo for the validator, with the callback setting the validator's `tombstoned` value.
