### ISSUE TITLE
Function HandleTokenizedShares can never be executed exactly

### ISSUE THREAD

**Issue by neitdung** [quicksilver-zone/quicksilver#654]
## Summary of Bug

Function HandleTokenizedShares can't be executed exactly because the condition below always returns false:

https://github.com/quicksilver-zone/quicksilver/blob/8fc6f208090cb3154fde917fbbeaad6b928421d4/x/interchainstaking/keeper/ibc_packet_handlers.go#L546-L547

The type of `sharesAmount` is `sdk.Coin` but type of `dist.Amount` is `uint64` so this condition always returns false. Then logic inside this function can't be run.

## Expected Behaviour

We should compare `sharesAmount.Amount` with `dist.Amount` then HandleTokenizedShares can be run with expected logic.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by hoangdv2429** [comment]
Do you want to open a PR for this @neitdung

**Comment by neitdung** [comment]
Yes, but I need to reseach more about LSM, denom of asset minted by cosmos-sdk LSM module is not like our qAssets, it's prefix is based on validator address

**Comment by hoangdv2429** [comment]
> Yes, but I need to reseach more about LSM, denom of asset minted by cosmos-sdk LSM module is not like our qAssets, it's prefix is based on validator address 

Great! Please self assign this request and if you need any help, please ask the team too.

**Comment by DongLieu** [comment]
I am also dealing with TestHandleCompleteSend() also facing the same situation
I think with only current context in [GetZoneFromContext()](https://github.com/quicksilver-zone/quicksilver/blob/main/x/interchainstaking/keeper/zones.go#L121) we can only get all zones

**Comment by joe-bowman** [comment]
Thanks @neitdung, great catch. The LSM-specific unbonding logic needs revisiting as it stands anyway. I will merge LSM changes in v1.2 to main very shortly; but thank you for finding this :)
