### ISSUE TITLE
We need a RemovePerformanceDelegation func to perform deletion.

### ISSUE THREAD

**Issue by DongLieu** [quicksilver-zone/quicksilver#757]
I see that in this line [here](https://github.com/quicksilver-zone/quicksilver/blob/main/x/interchainstaking/keeper/zones.go#L463) (func RemoveZoneAndAssociatedRecords) cannot be deleted PerformanceDelegation

because when setPerformanceDelegation uses types.GetPerformanceDelegationKey, setDelegation uses types.GetDelegationKey

 So we need a RemovePerformanceDelegation func to perform delegation.
 
 Context: #678

**Comment by ThanhNhann** [comment]
Nice catch 🔥
