### ISSUE TITLE
utils/addressutils: AccAddressFromBech32 should properly handle errors: benign error but that pattern is dangerous if accepted all over

### ISSUE THREAD

**Issue by odeke-em** [quicksilver-zone/quicksilver#855]
## Summary of Bug

https://github.com/quicksilver-zone/quicksilver/blob/009d7ef7c246eb66873a4fa37774c05718d3f135/utils/addressutils/address.go#L45-L48 should be more careful by checking that that error is nil before that conversion lest return nil, err

![image](https://github.com/quicksilver-zone/quicksilver/assets/4898263/c3e678ee-0063-49f1-a5c4-1528b931a2e8)

And https://github.com/quicksilver-zone/quicksilver/blob/009d7ef7c246eb66873a4fa37774c05718d3f135/utils/addressutils/address.go#L64-L67
![image](https://github.com/quicksilver-zone/quicksilver/assets/4898263/b187dc10-de13-4f0c-a27f-cf4929046758)
____

#### For Admin Use

- [x] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by joe-bowman** [comment]
This is only done here, because we know that AddressFromBech32 in the same file always returns nil if there is an error.

But will add the additional check in case the deeper function is ever changed.
